backend:
  name: github
  repo: tanadolforwork-crypto/Portfolio
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:

  - name: "profile"
    label: "Profile"
    files:
      - file: "content/profile.json"
        label: "Profile Data"
        name: "profile"
        fields:
          - { label: "ชื่อ", name: "name", widget: "string" }
          - { label: "ตำแหน่ง", name: "position", widget: "string" }
          - { label: "รายละเอียด", name: "description", widget: "text" }

  - name: "projects"
    label: "Projects"
    files:
      - file: "content/projects.json"
        label: "Project List"
        name: "projects"
        fields:
          - label: "รายการโปรเจกต์"
            name: "items"
            widget: "list"
            fields:
              - { label: "ชื่อโปรเจกต์", name: "title", widget: "string" }
              - { label: "รายละเอียด", name: "description", widget: "text" }
